---
- package:
    name: nginx
    state: present

- set_fact: nginx_prefix={{ nginx_setup[ansible_system]['prefix']| default('/') }}
- set_fact: nginx_user={{ nginx_setup[ansible_system]['user'] | default('nginx') }}

- file:
    state: directory
    name: "{{ nginx_prefix }}etc/nginx/conf.d/"

- template:
    dest: "{{ nginx_prefix }}etc/nginx/nginx.conf"
    src: nginx.conf
  notify: restart nginx

# since nginx is used on the builder and we remove ipv6
# we need to remove the default config who is using  ipv6
- name: Remove default configuration
  copy:
    dest: /etc/nginx/conf.d/default.conf
    content: ""
  when: ansible_system == 'Linux'
  notify: restart nginx

- service:
    name: nginx
    state: started
    enabled: yes

- include: firewall_linux.yml
  when: ansible_system == 'Linux'
