- name: Remove the default nagios apache configuration
  copy:
    dest: /etc/httpd/conf.d/nagios.conf
    content: ''

- name: Add nagios httpd configuration
  template:
    src: httpd.conf
    dest: /etc/httpd/conf.d/{{ ansible_fqdn }}.conf.d/nagios.conf
  notify: restart httpd

- package:
    name: python-passlib
    state: present

- htpasswd:
    path: /etc/nagios/htpasswd
    name: "nagios_admin"
    password: "{{ nagios_admin_password }}"
    owner: root
    group: apache
    mode: 0640

- htpasswd:
    path: /etc/nagios/htpasswd
    name: "guest"
    password: "gluster"
