- name: Create a public zone
  route53_zone:
    zone: aws.gluster.org
    comment: this is an test for now

- name: Create a public zone
  route53_zone:
    zone: int.aws.gluster.org
    comment: this is an test for now

- name: Get lists of existing VMs
  ec2_instance_info:
    region: "{{ aws_region }}"
    filters:
      "tag:Owner": "gluster-infra"
  register: vms

- name: Add the VMs to the internal zone
  route53:
    state: present
    record: "{{ item.tags.Name.split('.')[0] }}.int.aws.gluster.org"
    zone: "int.aws.gluster.org"
    type: A
    ttl: 7200
    value: "{{ item.private_ip_address }}"
  loop: "{{ vms.instances }}"
