- name: Create a public zone
  route53_zone:
    zone: aws.gluster.org
    comment: this is an test for now

- name: Create a public zone
  route53_zone:
    zone: int.aws.gluster.org
    comment: this is an test for now
