---
- src: https://github.com/OSAS/ansible-role-ansible_bastion
  name: bastion
- src: https://github.com/OSAS/ansible-role-salt_transport
  name: salt_transport
- src: git+https://gitlab.com/OSAS/ansible-role-tor.git
  name: tor
- src: git+https://gitlab.com/misc/ansible-role-shell_timeout.git
  name: shell_timeout
- src: https://github.com/OSAS/ansible-role-httpd
  name: httpd
- src: https://github.com/OSAS/ansible-role-freeipa
  name: freeipa
- src: https://github.com/OSAS/ansible-role-openssh
  name: openssh
- src: https://github.com/OSAS/ansible-role-selinux
  name: selinux
- src: https://github.com/OSAS/ansible-role-rsyslog
  name: rsyslog
- src: https://github.com/OSAS/ansible-role-middleman_builder
  name: builder
- src: git+https://gitlab.com/osas/ansible-role-ntp.git
  name: ntp
- src: git+https://gitlab.com/misc/ansible-role-systemd_container.git
  name: systemd_container
- src: git+https://gitlab.com/osas/ansible-role-libvirt.git
  name: libvirt
- src: git+https://gitlab.com/osas/ansible-role-munin.git
  name: munin
- src: git+https://gitlab.com/osas/ansible-role-lvm_config.git
  name: lvm_config
- src: git+https://gitlab.com/osas/ansible-role-memcached.git
  name: memcached
- src: git+https://gitlab.com/osas/ansible-role-pf_firewall.git
  name: pf_firewall
- src: git+https://gitlab.com/misc/ansible-role-unattended_updates.git
  name: unattended_updates
  version: fix_yum_cron
- src: git+https://gitlab.com/osas/ansible-role-salt.git
  name: salt
- src: git+https://gitlab.com/osas/ansible-role-postgrey.git
  name: postgrey
- src: git+https://gitlab.com/osas/ansible-role-guest_virt_install.git
  name: guest_virt_install
- src: git+https://gitlab.com/osas/ansible-role-xinetd.git
  name: xinetd
- src: git+https://gitlab.com/misc/ansible-role-postgresql.git
  name: postgresql
  version: open_network
# move to OSAS once https://github.com/OSAS/ansible-role-mariadb/pull/2 is merged
# and https://github.com/OSAS/ansible-role-mariadb/pull/3
- src: https://github.com/mscherer/ansible-role-mariadb
  name: mariadb
  version: fix_misc
