---
- src: https://github.com/OSAS/ansible-role-ansible_bastion
  name: bastion
- src: https://github.com/OSAS/ansible-role-salt_transport
  name: salt_transport
- src: https://github.com/OSAS/ansible-role-httpd
  name: httpd
- src: https://github.com/OSAS/ansible-role-freeipa
  name: freeipa
- src: https://github.com/OSAS/ansible-role-openssh
  name: openssh
