---
- src: https://github.com/OSAS/ansible-role-ansible_bastion
  name: bastion
- src: https://github.com/OSAS/ansible-role-salt_transport
  name: salt_transport
- src: git+https://gitlab.com/misc/ansible-role-tor.git
  name: tor
- src: https://github.com/OSAS/ansible-role-httpd
  name: httpd
- src: https://github.com/OSAS/ansible-role-freeipa
  name: freeipa
- src: https://github.com/OSAS/ansible-role-openssh
  name: openssh
- src: https://github.com/OSAS/ansible-role-selinux
  name: selinux
- src: https://github.com/OSAS/ansible-role-rsyslog
  name: rsyslog
- src: https://github.com/OSAS/ansible-role-middleman_builder
  name: builder
- src: git+https://gitlab.com/misc/ansible-role-ntp.git
  name: ntp
