---
- src: https://github.com/OSAS/ansible-role-ansible_bastion
  name: bastion
- src: https://github.com/OSAS/ansible-role-salt_transport
  name: salt_transport
- src: git+https://gitlab.com/misc/ansible-role-tor.git
  name: tor
- src: git+https://gitlab.com/misc/ansible-role-shell_timeout.git
  name: shell_timeout
- src: https://github.com/OSAS/ansible-role-httpd
  name: httpd
- src: https://github.com/OSAS/ansible-role-freeipa
  name: freeipa
- src: https://github.com/OSAS/ansible-role-openssh
  name: openssh
- src: https://github.com/OSAS/ansible-role-selinux
  name: selinux
- src: https://github.com/OSAS/ansible-role-rsyslog
  name: rsyslog
- src: https://github.com/OSAS/ansible-role-middleman_builder
  name: builder
- src: git+https://gitlab.com/osas/ansible-role-ntp.git
  name: ntp
- src: git+https://gitlab.com/misc/ansible-role-systemd_container.git
  name: systemd_container
- src: git+https://gitlab.com/osas/ansible-role-libvirt.git
  name: libvirt
- src: git+https://gitlab.com/osas/ansible-role-munin.git
  name: munin
- src: git+https://gitlab.com/osas/ansible-role-lvm_config.git
  name: lvm_config
- src: git+https://gitlab.com/misc/ansible-role-memcached.git
  name: memcached
- src: git+https://gitlab.com/misc/ansible-role-pf_firewall.git
  name: pf_firewall
