---
- package:
    name: nginx
    state: present

- set_fact: 
    nginx_prefix: "{{ nginx_setup[ansible_system]['prefix']| default('/') }}"
    nginx_user: "{{ nginx_setup[ansible_system]['user'] | default('nginx') }}"

- file:
    state: directory
    name: "{{ nginx_prefix }}etc/nginx/conf.d/"

- service:
    name: nginx
    state: started
    enabled: yes

- include_tasks: firewall_linux.yml
  when: ansible_system == 'Linux'
