- name: Creates the lists
  command: /usr/lib/mailman/bin/newlist {{ item }} list-admin@{{ mail_domain }} {{ item }}
  args:
    creates: /var/lib/mailman/lists/{{ item }}/config.pck
  with_items: mailing_lists
