---
- ec2_group:
    name: ansible-gluster-builders-sg
    description: Ansible managed security group for builders
    vpc_id: "{{ vpc_id }}"
    region: "{{ aws_region }}"
    rules:
    - proto: tcp
      ports:
      - 22
      cidr_ip: 0.0.0.0/0
      rule_desc: allow all on port 22

- ec2_group:
    name: ansible-gluster-openvpn-sg
    description: Ansible managed security group for openvpn nodes
    vpc_id: "{{ vpc_id }}"
    region: "{{ aws_region }}"
    rules:
    - proto: tcp
      ports:
      - 22
      cidr_ip: 0.0.0.0/0
      rule_desc: allow all for ssh
    - proto: tcp
      ports:
      - 1194
      cidr_ip: 0.0.0.0/0
      rule_desc: allow all for openvpn

