---
- name: Install jenkins builder standard packages
  package:
    state: present
    name:
    - git
    - dbench
    - yajl
    - sudo
    - automake
    - autoconf
    - libtool
    - bison
    
- name: Enable SCL
  package:
    state: present
    name: centos-release-scl
  when: '"jenkins_builders_rht" in group_names and ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"'

- name: Add packages specific to rht builders
  package:
    state: present
    name:
    - python27
    - python-libcloud
    - python-docopt
  when: '"jenkins_builders_rht" in group_names and ansible_distribution == "CentOS"'

- name: Install jenkins builder Linux packages
  package:
    state: present
    name:
    # used to be pulled by openssl
    - make
    # needed for some tests
    - net-tools
    # used for smoke.sh, for killall
    - psmisc
    - libacl-devel
    - nfs-utils
    - flex
    - perl-Test-Harness
    - openssl-devel
    - lvm2-devel
    - sqlite-devel
    - libxml2-devel
    - python-devel
    - userspace-rcu-devel
    - libibverbs-devel
    - librdmacm-devel
    - libaio-devel
    - xfsprogs
    # used for testing eventing
    - python-requests
    - python-flask
    - python-prettytable
    # used for build-jobs testing
    - python-virtualenv
    #  - python-argparse
    # used for utils/create-files.py
    - pyxattr
    # used for regression testing
    - attr
    # used for cli
    - ncurses-devel
    - readline-devel
    # tmpwatch to clean /tmp
    - tmpwatch
    - bc
    # required for https://review.gluster.org/#/c/18532/
    - libcurl-devel
    # required for pstack, used to be pulled by rpm-build
    - gdb
  when: ansible_system == 'Linux'

- include: pkgs_job_cppcheck.yml
  when: ansible_system == 'Linux'

- include: pkgs_job_rpms.yml
  when: ansible_system == 'Linux'

- include: pkgs_job_lcov.yml
  when: '"jenkins_builders_lcov" in group_names'
  
- name: Install jenkins builder Fedora packages
  package:
    state: present
    name:
    - libtirpc-devel
    - rpcgen
# needed for smoke testing on Fedora
# https://bugzilla.redhat.com/show_bug.cgi?id=1623487
    - python3-devel
    - python3-pylint
    - git-clang-format
    - libtsan
# python3 pyxattr package needed  to run few tests in line coverage job
    - python3-pyxattr
  when: ansible_system == 'Linux' and ansible_distribution == 'Fedora'

- name: Install jenkins builder Centos packages
  package:
    state: present
    name:
    - python-argparse
    # packages for python3 environment
    - python36-devel
    - python36-prettytable
  when: ansible_system == 'Linux' and ansible_distribution == 'CentOS'

- package:
    state: present
    name: "{{ item }}"
  name: Install jenkins builder FreeBSD packages
  when: ansible_system == 'FreeBSD'
  with_items:
  - perl5
  - sqlite3
  - pkgconf
  - liburcu
  - gmake
# our build script do not seems to work with clang, due to some weird
# argp issue
  - gcc
# adding because it is present on freebsd0.cloud, for parity
  - gsed
  - curl
# requested on https://bugzilla.redhat.com/show_bug.cgi?id=1608707
# debundling
  - e2fsprogs-libuuid
# requested on https://bugzilla.redhat.com/show_bug.cgi?id=1609347
  - argp-standalone

- name: Remove package that cause trouble with the regression suite
  package:
    state: absent
    name:
    - qemu-img
    - glusterfs-libs
    - glusterfs
    - glusterfs-api
    - glusterfs-client-xlators
