---
- name: Deploy the check_selinux script
  copy:
    dest: /usr/local/bin/check_selinux
    src: check_selinux
    mode: 0755 
    owner: root
    group: root
    setype: nagios_unconfined_plugin_exec_t
  
- name: Set the file context for check_selinux
  sefcontext:
    target: /usr/local/bin/check_selinux
    setype: nagios_unconfined_plugin_exec_t
    state: present
  
- name: Add the nrpe config for check_selinux
  copy:
    dest: /etc/nrpe.d/check_selinux.cfg
    src: check_selinux.cfg
    mode: 0644
    owner: root
    group: nrpe
  notify: Restart nrpe

- name: Deploy NRPE check on nagios server for SELinux
  template:
    dest: /etc/nagios/conf.d/{{ inventory_hostname }}_nrpe_selinux.cfg
    src: nrpe_selinux.cfg
  delegate_to: "{{ item }}"
  notify: Verify config and restart nagios
  with_items: "{{ nagios_server }}"
