---
- name: Install munin plugin for unbound
  package:
    name: unbound-munin
    state: installed

- name: Add links to enable the plugin
  shell: for i in /usr/share/munin/plugins/unbound_*; do ln -s $i; done
  args:
    chdir: /etc/munin/plugins/
    creates: /etc/munin/plugins/unbound_munin_queue

# TODO restart munin ?
