---
- name: Define libvirt network for internal
  virt_net:
    command: define
    state: present
    name: internal
    xml: '{{ lookup("template", "internal.xml") }}'
  notify: Reload libvirtd

- name:
  virt_net:
    autostart: True
    name: internal
