---
#
# Some VM on rackspace do get a configuration telling
#  "use dhcp", but there is no actual dhcp server for them
# So we are switching to static ip, and be done with it
#
- name: Disable network configuration from cloud-init
  copy:
    dest: /etc/cloud/cloud.cfg.d/99_gluster.cfg
    content: "network: { config: disabled }"

- name: Enable static configuration
  template:
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    src: ifcfg
