---
- name: Install conntrackd
  package:
    name: conntrack-tools
    state: installed

- name: Deploy conntrackd configuration
  template:
    src: conntrackd.conf
    dest: /etc/conntrackd/conntrackd.conf
  notify: Restart conntrackd

#TODO open the firewall
- name: Make sure the service is started
  service:
    name: conntrackd
    enabled: True
    state: started
