---
- name: Load NRPE vars
  include_vars: "{{ item }}"
  with_first_found:
  - "{{ ansible_system }}.yml"
  - "defaults.yml"

- name: Install NRPE and plugins
  package:
    state: present
    name: "{{ pkg_name }}"

- name: Fix allowed_hosts in NRPE
  lineinfile:
    dest: "{{ conf_location }}"
    regexp: "^allowed_hosts="
    line: "allowed_hosts=127.0.0.1,{{ nagios_ip }}"
  notify: Restart nrpe

- name: Fix include_dir in NRPE on FreeBSD
  lineinfile:
    dest: "{{ conf_location }}"
    regexp: "^include_dir="
    line: "include_dir=/etc/nrpe.d/"
  notify: Restart nrpe
  when: ansible_system == 'FreeBSD'

- name: Create dir
  file:
    state: directory
    name: /etc/nrpe.d/
  when: ansible_system == 'FreeBSD'

- name: Add configuration for default checks
  template:
    dest: /etc/nrpe.d/{{ item.check }}.cfg
    src: check_base.cfg
  notify: Restart nrpe
  with_items: "{{ nrpe_services }}"

- name: Create nrpe.service.d
  file:
    name: /etc/systemd/system/nrpe.service.d/
    state: directory
  when: ansible_service_mgr == 'systemd'

- name: Deploy systemd configuration to auto restart
  copy:
    dest: /etc/systemd/system/nrpe.service.d/restart.conf
    src: restart.conf
  notify: Reload systemd and restart
  when: ansible_service_mgr == 'systemd'

- name: Start NRPE service
  service:
    name: "{{ service_name }}"
    state: started
    enabled: yes

# FreeBSD is handled outside of this role
- name: Open firewall for NRPE (lokkit)
  shell: "lokkit -p 5666:tcp"
  when: ansible_distribution_major_version == '6' and (ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat')

- name: Open firewall for NRPE (firewalld)
  firewalld:
    permanent: True
    immediate: True
    state: enabled
    rich_rule: 'rule family="ipv4" port port=5666 protocol=tcp source address="{{ nagios_ip }}" accept'
    zone: "{{ nrpe_fw_zone | default(omit) }}"
  when: ansible_distribution == 'Fedora' or (ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 7)

- name: Deploy NRPE check on nagios server
  template:
    dest: /etc/nagios/conf.d/{{ inventory_hostname }}_base_nrpe.cfg
    src: nagios_base_nrpe.cfg 
  delegate_to: "{{ item }}"
  notify: Verify config and restart nagios
  with_items: "{{ nagios_server }}"

