---
- name: Install NRPE and plugins
  package:
    state: installed
    name:
    - nrpe
    - nagios-plugins-load
    - nagios-plugins-uptime
    - nagios-plugins-check-updates
    - nagios-plugins-procs
    - nagios-plugins-file_age
    - nagios-plugins-swap
    - nagios-plugins-mailq

- name: Fix allowed_hosts in NRPE
  lineinfile:
    dest: /etc/nagios/nrpe.cfg
    regexp: "^allowed_hosts="
    line: "allowed_hosts=127.0.0.1,{{ nagios_ip }}"
  notify: Restart nrpe

- name: Add configuration for default checks
  template:
    dest: /etc/nrpe.d/{{ item.check }}.cfg
    src: check_base.cfg
  notify: Restart nrpe
  with_items: "{{ nrpe_services }}"

- name: Start NRPE service
  service:
    name: nrpe
    state: started
    enabled: yes

- name: Open firewall for NRPE (lokkit)
  shell: "lokkit -p 5666:tcp"
  when: ansible_distribution_major_version == '6' and (ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat')

- name: Open firewall for NRPE (firewalld)
  firewalld:
    permanent: True
    immediate: True
    state: enabled
    rich_rule: 'rule family="ipv4" port port=5666 protocol=tcp source address="{{ nagios_ip }}" accept'
  when: ansible_distribution == 'Fedora' or ansible_distribution_major_version == '7'

- name: Deploy NRPE check on nagios server
  template:
    dest: /etc/nagios/conf.d/{{ inventory_hostname }}_base_nrpe.cfg
    src: nagios_base_nrpe.cfg 
  delegate_to: "{{ item }}"
  notify: Verify config and restart nagios
  with_items: "{{ nagios_server }}"
