---
# this is used along the salt setup to say "stop managing this 
# system, it is now in ansible". Since the openssh setup in salt break
# freeipa, and I cannot fix until that's upgraded all over the board, 
# I have to disable the states 
- lineinfile:
    dest: /etc/salt/grains
    line: "cfgmgmt: ansible"
    create: yes
    insertafter: EOF
