---
dependencies:
- role: guest_virt_install
  vars:
    name: "builder{{ number }}.int.rht.gluster.org"
  system_disk_size: 30
  volgroup: "{{ vm_storage_vg }}"
  mem_size: 2048
  num_cpus: 2
  bridge: "{{ bridge_common }}"
  sshkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  network:
    # due to bad planning for the ip numbering, we have builder starting at 100, until 40 where they
    # go back to 80
    ip: 172.24.1.{{ (100 + number) if (number < 40) else (40 + number) }}/24
    gateway: 172.24.1.181
    nameservers:
    - 172.24.1.60
    - 172.24.1.61

