---
dependencies:
- role: guest_virt_install
  name: builder{{ number }}.int.rht.gluster.org
  system_disk_size: 30
  volgroup: "{{ vm_storage_vg }}"
  mem_size: 2048
  num_cpus: 2
  distribution: Centos
  bridge: "{{ bridge_common }}"
  sshkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  network:
    bootproto: static
    ip: 172.24.1.{{ 100 + number }}/24
    gateway: 172.24.1.181
    nameservers:
    - 8.8.8.8
    - 8.8.4.4

