---
- name: See if we are the master
  set_fact:
    is_master: "{{ ansible_hostname == master }}"

- name: Generate a random password
  set_fact:
    password: "{{ lookup('password', '~/keepalived_pass' + master + 'length=6') }}"

- name: Install keepalived
  package:
    name: keepalived
    state: installed

- name: Deploy configuration
  template:
    dest: /etc/keepalived/keepalived.conf
    src: keepalived.conf
  notify: Restart keepalived

- name: Deploy the script to sync conntrack
  copy:
    dest: /usr/libexec/keepalived/wrapper_conntrackd.sh
    src: wrapper_conntrackd.sh
    mode: 0755

- name: Open vrrp for firewalld 
  firewalld:
    rich_rule: 'rule family=ipv4 protocol value="vrrp" destination address="224.0.0.18" accept'
    permanent: True
    state: enabled
    immediate: True
    zone: dmz 

- name: Start service
  service:
    name: keepalived
    enabled: True
    state: started

- name: Make sure services can start and listen to the floating ips
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: 1
