---
- name: Deploy gerrit specific config for proxy
  template:
    dest: "{{ _vhost_confdir }}/mod_proxy_gerrit.conf"
    src: mod_proxy.conf.j2
    mode: 0644
  notify: verify config and restart httpd
