---
- include: fix_httpd.yml

- name: Install Java and python-bugzilla
  package:
    state: present
    name: "{{ item }}"
  with_items:
  - java-1.8.0-openjdk
  - python-bugzilla
  - postgresql
  - git

- name: Create a user for review
  user:
    name: "{{gerrit_user}}"
    home: "{{gerrit_user_home}}"

# absolute path of where gerrit is installed
- name: Set gerrit_dir
  set_fact:
    _gerrit_dir: "{{ gerrit_user_home }}/{{ gerrit_home }}"

- name: Setup the selinux boolean for proxying
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: Check if Gerrit is installed
  stat:
    path: "{{ _gerrit_dir }}"
  register: gerrit_status

- name: "Fail when Gerrit is not setup"
  fail:
    msg: "Please setup Gerrit at {{ _gerrit_dir }}"
  when: gerrit_status.stat.exists == False

- name: Setup the gerrit.config file
  template:
    src: gerrit.config.j2
    dest: "{{ _gerrit_dir }}/etc/gerrit.config"
    owner: "{{gerrit_user}}"
    mode: 0644
  notify: restart gerrit

- include: replication.yml
  when: gerrit_replication is defined

- name: Cron to delete old log files
  cron:
    name: "Clean logs"
    special_time: "weekly"
    job: "find {{ _gerrit_dir }}/logs -mtime +15 -delete"
    user: "{{gerrit_user}}"

- name: Setup python-bugzilla
  command: "bugzilla login {{bugzilla_user}} {{bugzilla_pass}}"
  args:
    creates: "{{gerrit_user_home}}/.bugzillacookies"
  when: bugzilla_user is defined
  no_log: True

- name: Set the SELinux policy for cgit
  sefcontext:
    target: "{{ _gerrit_dir }}/git"
    setype: git_sys_content_t
    state: present
