---
dependencies:
- role: guest_virt_install
  bridge: "{{ bridge_public }}"
  volgroup: "{{ vm_storage_vg }}"
  system_disk_size: 10
  data_disk_size: 1
  mem_size: 1024
  num_cpus: 1
#  distribution: Centos
#  version: 7
  sshkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
- role: guest_add_bridge
  bridge: "{{ bridge_common }}"

