---
- name: Install nftables
  package:
    name: nftables
    state: present

- name: Deploy firewall rules
  template:
    dest: /etc/sysconfig/nftables.conf
    src: nftables.conf
# do not apply until ready
#  notify: Reload and verify nftables

# do not start until everything is ready
- name: Start nftables service
  service:
    name: nftables
    state: stopped
    enabled: False

# remove firewalld once that's ready
#- name: Remove firewalld
#  package:
#    name: firewalld
#    state: absent
