---
- name: Set common interface to the internal zone
  firewalld:
    zone: dmz
    interface: eth1
    permanent: True
    immediate: True
    state: enabled

# since the DMZ must connect, masquerade
# must be on the public zone. But we can't use masquerade
# as it do not reuse the right IP for forwarding.
- name: Tag packet to nat
  firewalld_direct:
    chain: FORWARD_direct
    args: '-i eth1 -o eth0 -j MARK --set-mark 1'
    state: present

- name: Nat tagged packet
  firewalld_direct:
    chain: POSTROUTING_direct
    table: nat
    args: '-m mark --mark 1 -j SNAT --to-source 8.43.85.181'
    state: present

- name: Tag packet to nat (permanent)
  firewalld_direct:
    chain: FORWARD_direct
    args: '-i eth1 -o eth0 -j MARK --set-mark 1'
    permanent: True
    state: present

- name: Nat tagged packet (permanent)
  firewalld_direct:
    chain: POSTROUTING_direct
    table: nat
    args: '-m mark --mark 1 -j SNAT --to-source 8.43.85.181'
    permanent: True
    state: present

- name: Set public interface to the public zone
  firewalld:
    zone: public
    interface: eth0
    permanent: True
    immediate: True
    state: enabled

- name: Setup logging rule to create the firewall
  firewalld:
    zone: dmz
    rich_rule: 'rule family="ipv4" source address="172.24.1.0/24" log prefix="test" level="info" limit value="1/m" accept'
    permanent: true
    state: enabled
    immediate: True
