---
- name: Create bitergia user for rsync
  user:
    state: present
    comment: Bitergia user to sync logs
    home: /srv/bitergia/
    name: bitergia

- name: Add the bitergia ssh keys
  authorized_key: 
    user: bitergia
    key: "{{ item }}"
  with_file:
  - bot.pub
  - daniel.pub

- name: Install script to clean logs
  copy:
    dest: /usr/local/bin/bitergia_clean.pl
    src: bitergia_clean.pl

- name: Install cron to clean logs
  cron:
    name: Clean logs
    user: bitergia
    job: perl /usr/local/bin/bitergia_clean.pl
    hour: '5'

- name: Install cron to copy the file
  cron:
    name: Copy bitergia file
    user: root
    job:  /bin/cp -f -R /var/log/httpd ~bitergia/logs && chown -R bitergia ~bitergia/
    minute: '*/30'
