---
- package:
    name: "{{ item }}"
    state: installed
  with_items:
  - cgit

- name: Include cgitrepos file
  lineinfile:
    dest: /etc/cgitrc
    line: "include=/etc/cgitrepos"

- name: Template the /etc/cgitrepos file
  template:
    mode: 0644
    src: cgitrepos
    dest: /etc/cgitrepos

- name: Template the apache config file
  template:
    mode: 0644
    src: cgit.httpd.conf
    dest: /etc/httpd/conf.d/cgit.conf
  notify: verify config and restart httpd

# specific config for dev.gluster.org
- include: fix_review.yml
