---
dependencies:
- role: httpd
  redirects:
  - src: '^/$'
    target: '/mailman/listinfo'
    match: True
- role: blacklist_httpd
  rbl:
  - "b.barracudacentral.org"
  - "cbl.abuseat.org"
  - "dnsbl.dronebl.org"
