- name: Deploy NRPE check checks
  template:
    dest: /etc/nrpe.d/check_connect_ssh_{{ item.name }}.cfg
    src: check_connect_ssh.cfg
    mode: 0644 
    owner: root
    group: nrpe
  with_items: 
  - "{{ ssh_targets }}"
  notify: Restart nrpe

- name: Deploy NRPE check on nagios server
  template:
    dest: /etc/nagios/conf.d/{{ inventory_hostname }}_nrpe_connect_ssh.cfg
    src: nrpe_connect_ssh.cfg 
  delegate_to: "{{ item }}"
  notify: Verify config and restart nagios
  with_items: "{{ nagios_server }}"
