# so lokkit in EL6 has a interesting bug, every time lokkit
# is run, it kill existing connexion, since it doesn't take
# conntrack in account
# Sadly, no one applied nor backported
# https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/GD5FWJHKWJXMQ3UCJSQ74QWMLDFY4KCN/
---
- package: state=present name={{ item }}
  with_items:
  - system-config-firewall-base
  - iptables-ipv6

- name: Copy custom rules for lokkit
  copy: dest=/etc/sysconfig/ipv4_conntrack content="-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT"
  notify: Include conntrack rules in lokkit

# so on iptables restart, the conntrack table is dropped
# so this break salt...
- name: Do not kill conntrack on firewall restart
  lineinfile: 
    dest: /etc/syconfig/iptables-config
    regexp: '^IPTABLES_MODULES_UNLOAD='
    line: 'IPTABLES_MODULES_UNLOAD="no"'
    state: present

- name: Apply change immediately
  meta: flush_handlers
