---
- include_tasks: pkgs.yml

- include_tasks: lokkit.yml
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'

- include_tasks: root_ssh_keys.yml
# for now, the code only work on Linux

- include_tasks: timezone.yml

- include_tasks: disable_weak_deps.yml
  when: ansible_pkg_mgr == 'dnf'
 
- include_tasks: freebsd.yml
  when: ansible_system == 'FreeBSD'
