---
- package:
    state: present
    name: epel-release
  when: ansible_distribution == 'CentOS'

- package:
    state: present
    name: "{{ item }}"
  with_items:
  - python3-libselinux
  - python3-policycoreutils
  when: ansible_distribution == 'Fedora'

- package:
    state: present
    name: "{{ item }}"
  with_items:
  - lsof
  - screen
  - htop
  - nmap
  - socat

- package:
    state: present
    name: "{{ item }}"
  with_items:
  - strace
  - vim-enhanced
  - lshw
  - rsync
  when: ansible_system == 'Linux'
