---
- package:
    state: present
    name: epel-release
  when: ansible_distribution == 'CentOS'

- package:
    state: present
    name: "{{ item }}"
  with_items:
  - python3-libselinux
  - python3-policycoreutils
  when: ansible_distribution == 'Fedora'

# remove because we use ntpd
- package:
    state: absent
    name: "{{ item }}"
  with_items:
  - chrony
  when: ansible_distribution == 'Fedora'

- package:
    state: present
    name: "{{ item }}"
  with_items:
  - lsof
  - screen
  - htop
  - nmap
  - socat

- package:
    state: present
    name: "{{ item }}"
  with_items:
  - strace
  - lshw
  - rsync
  when: ansible_system == 'Linux'

- package:
    state: present
    name: "{{ item }}"
  with_items:
  - vim-enhanced
  when: ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS'

- package:
    state: present
    name: "{{ item }}"
  with_items:
  - vim-nox
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
