---
- name: Install root ssh keys
  authorized_key: 
    user: root
    key: "{{ item }}"
  with_file:
  - misc_main.pub
  - misc_backup.pub
  - deepshikha.pub
  - ant-queen.pub
  - ant-queen-2019.pub
 
- name: Remove old keys
  authorized_key:
    user: root
    key: "{{ item }}"
    state: absent
  with_file:
  - nigel.pub
  - misc_nano_old.pub
  - misc_tpm_old.pub
