- hosts: all:!cage_externally_facing
  roles:
  - openssh

- hosts: cage_externally_facing
  roles:
  - role: openssh
    filters: "{{ ssh_ciphers_filter }}"
    when: ansible_fqdn != 'gerrit-new.rht.gluster.org'

- hosts: all
  roles:
  - base
  - role: selinux
    when: ansible_system == 'Linux' and ansible_distribution != 'Debian'
  - ntp
  - role: shell_timeout
    when: ansible_system == 'Linux'
  - unattended_updates
  - ssh_keys_bastion
