---
- hosts: myrmicinae.rht.gluster.org
  roles:
  - role: guest_virt_install
    name: proxy.rht.gluster.org
    volgroup: myrmicinae
    disk_size: 10
    mem_size: 1024
    num_cpus: 1
    distribution: Centos
    version: 7
    bridge: virbr1
    sshkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    network:
      bootproto: static
      ip: 8.43.85.175/24
      gateway: 8.43.85.254
      nameservers:
      - 8.8.8.8
      - 8.8.4.4

- hosts: proxy.rht.gluster.org
  roles:
  - role: httpd
    website_domain: build.proxy.gluster.org
    use_letsencrypt: True
    force_tls: True
    reverse_proxy: http://8.43.85.172/
    # needed for letsencrypt, otherwise it complain about invalid email
    mail_domain: gluster.org
    use_mod_sec: True
    mod_sec_detection_only: True

  - role: httpd
    website_domain: dev.proxy.gluster.org
    use_letsencrypt: True
    force_tls: True
    reverse_proxy: http://8.43.85.171/
    # needed for letsencrypt, otherwise it complain about invalid email
    mail_domain: gluster.org
    use_mod_sec: True
    mod_sec_detection_only: True
