---
- hosts: myrmicinae.rht.gluster.org
  roles:
  - role: guest_virt_install
    name: proxy.rht.gluster.org
    volgroup: myrmicinae
    system_disk_size: 10
    mem_size: 1024
    num_cpus: 1
    distribution: Centos
    version: 7
    bridge: virbr1
    sshkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    network:
      bootproto: static
      ip: 8.43.85.175/24
      gateway: 8.43.85.254
      nameservers:
      - 8.8.8.8
      - 8.8.4.4

- hosts: proxy.rht.gluster.org
  roles:
  - role: httpd_proxy
    website_domain: build.proxy.gluster.org
    reverse_proxy: http://8.43.85.172/
    use_mod_sec: True
    mod_sec_detection_only: True

  - role: httpd_proxy
    website_domain: review.proxy.gluster.org
    reverse_proxy: http://gerrit.rht.gluster.org/
    use_mod_sec: True
    mod_sec_detection_only: True

  - role: httpd_proxy
    website_domain: fstat.gluster.org
    reverse_proxy: http://fstat.rht.gluster.org/

  - role: httpd_proxy
    website_domain: analysis.gluster.org
    reverse_proxy: http://analysis.rht.gluster.org/
