---
- hosts: myrmicinae.rht.gluster.org
  roles:
  - role: guest_proxy_rht
    name: proxy.rht.gluster.org
    distribution: Centos
    version: 7
    network:
      bootproto: static
      ip: 8.43.85.175/24
      gateway: 8.43.85.254

- hosts: myrmicinae.rht.gluster.org
  roles:
  - role: guest_proxy_rht
    name: proxy01.rht.gluster.org
    distribution: Fedora
    version: 26
    network:
      bootproto: static
      ip: 8.43.85.182/24
      gateway: 8.43.85.254

- hosts: formicary.rht.gluster.org
  roles:
  - role: guest_proxy_rht
    name: proxy02.rht.gluster.org
    distribution: Fedora
    version: 26
    network:
      bootproto: static
      ip: 8.43.85.183/24
      gateway: 8.43.85.254

- hosts: proxy_ha
  tasks:
  - name: Make sure the datadisk is present
    filesystem:
      fstype: ext4
      dev: "/dev/vdb"
  - name: Mount the fs
    mount: 
      name: /srv/
      src: /dev/vdb
      fstype: ext4
      state: mounted  
