- hosts: formicary.rht.gluster.org
  roles:
  - role: guest_virt_install
    vars:
      name: nagios.int.rht.gluster.org
    system_disk_size: 10
    data_disk_size: 1
    mem_size: 1024
    distribution: Centos
    version: 7
    bridge: "{{ bridge_common }}"
    network:
      ip: 172.24.1.63/24
      gateway: 172.24.1.181

- hosts: nagios.int.rht.gluster.org
  roles:
  - role: swap_file
    size: 1G
    path: /var/swap
