---
- hosts: proxy
  roles:
  - role: httpd_proxy
    website_domain: build.proxy.gluster.org
    reverse_proxy: http://8.43.85.172/
    use_mod_sec: True
    mod_sec_detection_only: True

  - role: httpd_proxy
    website_domain: review.proxy.gluster.org
    reverse_proxy: http://gerrit.rht.gluster.org/
    use_mod_sec: True
    mod_sec_detection_only: True

  - role: httpd_proxy
    website_domain: fstat.gluster.org
    reverse_proxy: http://fstat.rht.gluster.org/

  - role: httpd_proxy
    website_domain: analysis.gluster.org
    reverse_proxy: http://analysis.rht.gluster.org/
