---
- hosts: haplometrosis.rht.gluster.org
  roles:
  - role: guest_jenkins_builder_rht
    number: 0
  - role: guest_jenkins_builder_rht
    number: 1
  - role: guest_jenkins_builder_rht
    number: 2
  - role: guest_jenkins_builder_rht
    number: 3
  - role: guest_jenkins_builder_rht
    number: 4
  - role: guest_jenkins_builder_rht
    number: 5
  - role: guest_jenkins_builder_rht
    number: 6
  - role: guest_jenkins_builder_rht
    number: 7
  - role: guest_jenkins_builder_rht
    number: 8
  - role: guest_jenkins_builder_rht
    number: 9
