---
- hosts: formicary.rht.gluster.org
  roles:
  - role: guest_virt_install
    vars:
      name: backups.int.rht.gluster.org
    system_disk_size: 10
    # 1G for pgsql
    # 60G for binary
    # 6G for mls
    # 1G for mysql/wordpress
    data_disk_size: 75
    mem_size: 1024
    distribution: Centos
    version: 7
    bridge: "{{ bridge_common }}"
    network:
      ip: 172.24.1.51/24
      gateway: 172.24.1.181

- hosts: backups.int.rht.gluster.org
  tasks:
  - filesystem:
      dev: /dev/vdb
      fstype: lvm
  - lvg:
      vg: vg_data_backups.rht.gluster.org
      pvs: /dev/vdb
