#
# this host serve to build the website on middleman and deploy it live.
#
- hosts: webbuilder
  roles:
  - role: builder
    builder_name: gluster_planet
    git_url: "https://github.com/gluster/planet-gluster.git"
    git_version: master
    rsync_location: /var/www/planet
    rsync_server: http.int.rht.gluster.org
    rsync_user: deploy_website
    # push rebuild every hour
    rebuild_interval: 1
