- hosts: all:!int_rht_gluster_org
  roles:
  - role: munin
    munin_master: munin.gluster.org
#    admin_email: root@{{ ansible_domain }}
    diskstats_exclude: "mapper_patchy_,patchy_"

- hosts: munin.gluster.org
  roles:
  - role: swap_file
    size: 1G
    path: /var/swap
  - role: fix_rackspace_net
