---
- hosts: myrmicinae.rht.gluster.org
  roles:
  - role: guest_virt_install
    name: postgresql.rht.gluster.org
    system_disk_size: 20
    mem_size: 2048
    num_cpus: 1
    distribution: Centos
    version: 7
    bridge: "{{ bridge_public }}"
    network:
      bootproto: static
      ip: 8.43.85.170/24
      gateway: 8.43.85.254


