---
- hosts: formicary.rht.gluster.org
  roles:
  - role: guest_virt_install
    vars:
      name: munin.int.rht.gluster.org
    system_disk_size: 10
    data_disk_size: 10
    mem_size: 1024
    distribution: Centos
    version: 7
    bridge: "{{ bridge_common }}"
    network:
      ip: 172.24.1.59/24
      gateway: 172.24.1.181

- hosts: munin.int.rht.gluster.org
  tasks:
  # uncomment once 2.5 is out
  - filesystem:
      dev: /dev/vdb
      fstype: lvm
  - lvg:
      vg: vg_data_munin.int.rht.gluster.org
      pvs: /dev/vdb
  - file:
      path: /var/lib/munin
      state: directory
  - mount:
      path: /var/lib/munin
      src: /dev/vdb
      fstype: xfs
      state: mounted
