---
- hosts: http.int.rht.gluster.org
  roles:
  - role: scp_http_int
  - role: httpd
    website_domain: http.int.rht.gluster.org
    document_root: /var/www/glusterfs-logs
  - role: httpd_enable_index
    website_domain: bits.int.rht.gluster.org
    document_root: /var/www/bits

