- hosts: myrmicinae.rht.gluster.org
  roles:
  - role: guest_virt_install
    name: ant-queen.rht.gluster.org
    volgroup: myrmicinae
    system_disk_size: 10
    mem_size: 1024
    num_cpus: 1
    distribution: Centos
    version: 7
    bridge: virbr0
    sshkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    network:
      bootproto: static
      ip: 192.168.122.10/24
      gateway: 192.168.122.1
      nameservers:
      - 192.168.122.1

- hosts: bastion
  roles:
  - role: bastion
    run_on_new_host:
    - deploy_base.yml
    - deploy_rsyslog.yml
    - deploy_freeipa.yml
    - deploy_munin.yml
    compat_disable: True
    ansible_committers_group: admins
    remotes:
    - { name: 'github', url: 'git@github.com:gluster/gluster.org_ansible_configuration.git'}
