---
- hosts: http.int.rht.gluster.org
  roles:
  - role: httpd_planet
    website_domain: planet.int.rht.gluster.org
    server_aliases:
    - planet.gluster.org
    sync_user: deploy_website
    document_root: /var/www/planet

- hosts: http.int.rht.gluster.org
  vars:
    website_domain: ci-logs.gluster.org
  roles:
  - role: scp_http_int
    target_name: ci-logs
    scp_dest: /var/www/glusterfs-logs

- hosts: http.int.rht.gluster.org
  vars:
    website_domain: bits.int.rht.gluster.org
    redirects:
    - src: '^/$'
      target: '/pub'
      match: True
  roles:
  - role: scp_http_int
    scp_dest: /var/www/bits
    user: _bits-gluster
    target_name: bits
