---
- hosts: haplometrosis.rht.gluster.org
  roles:
  - role: guest_jenkins_builder_int_rht
    number: 0
    version: 6
  - role: guest_jenkins_builder_int_rht
    number: 1
    version: 6

  - role: guest_jenkins_builder_int_rht
    number: 2
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 3
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 4
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 5
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 6
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 7
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 8
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 9
    version: 7

- hosts: jenkins_builders_rht
  tasks:
  - name: Resize the disk of the builders
    lvol:
      vg: "vg_root_{{ ansible_fqdn }}"
      lv: root
      size: 18G
    when: ansible_system == 'Linux'
  - name: Make sure the filesystem is resized
    filesystem:
      fstype: ext4
      dev: "/dev/mapper/vg_root_{{ ansible_fqdn }}-root"
      resizefs: True
    when: ansible_system == 'Linux'

