---
- hosts: myrmicinae.rht.gluster.org
  roles:
  - role: guest_virt_install
    name: bugziller.rht.gluster.org
    volgroup: myrmicinae
    disk_size: 10
    mem_size: 1024
    num_cpus: 1
    distribution: Centos
    version: 7
    bridge: virbr0
    sshkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    network:
      bootproto: dhcp
