- hosts: bastion
  roles:
  - role: bastion
    run_on_new_host:
    - deploy_base.yml
    - deploy_rsyslog.yml
    - deploy_freeipa.yml
    - deploy_munin.yml
    compat_disable: True
    ansible_committers_group: admins
    remotes:
    - { name: 'github', url: 'git@github.com:gluster/gluster.org_ansible_configuration.git'}
  - role: polyinst_tmp
  - role: set_proxy
