---
- hosts: myrmicinae.rht.gluster.org
  roles:
  - role: guest_virt_install
    name: jenkins-stage.rht.gluster.org
    volgroup: myrmicinae
    system_disk_size: 10
    data_disk_size: 100
    mem_size: 4096
    num_cpus: 1
    distribution: Centos
    version: 7
    bridge: virbr1
    sshkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    network:
      bootproto: static
      ip: 8.43.85.177/24
      gateway: 8.43.85.254
      nameservers:
      - 8.8.8.8
      - 8.8.4.4

- hosts: jenkins-stage.rht.gluster.org
  tasks:
  # uncomment once https://github.com/ansible/ansible/pull/21620 is merged
  
  #- filesystem:
  #  dev: /dev/vdb
  #  fstype: lvm
  - lvg:
      vg: vg_data_jenkins-stage.rht.gluster.org
      pvs: /dev/vdb
  - lvol:
      vg: vg_data_jenkins-stage.rht.gluster.org
      lv: var_lib_jenkins
      size: 100%VG
  - filesystem:
      fstype: xfs
      dev: /dev/mapper/vg_data_jenkins--stage.rht.gluster.org-var_lib_jenkins
  - mount:
      name: /var/lib/jenkins
      src: /dev/mapper/vg_data_jenkins--stage.rht.gluster.org-var_lib_jenkins
      fstype: xfs
      state: present
