---
- hosts: myrmicinae.rht.gluster.org
  roles:
  - role: guest_virt_install
    vars:
      name: postgresql.rht.gluster.org
    system_disk_size: 20
    mem_size: 2048
    distribution: Centos
    version: 7
    bridge: "{{ bridge_public }}"
    network:
      ip: 8.43.85.170/24
      gateway: 8.43.85.254


