---
- hosts: nagios
  roles:
  - role: nagios
    websites:
    - {host: www.gluster.org, use_ssl: True}
    - {host: review.gluster.org, use_ssl: True}
    - {host: build.gluster.org, use_ssl: True}
    - {host: munin.gluster.org, use_ssl: True}
    - {host: download.gluster.org, use_ssl: True}
#   see private repo for the lists of admins
#    admins:

