---
- hosts: haplometrosis.rht.gluster.org
  roles:
  - role: guest_virt_install
    vars:
      name: softserve.rht.gluster.org
    system_disk_size: 10
    mem_size: 1024
    distribution: Centos
    version: 7
    bridge: "{{ bridge_public }}"
    network:
      ip: 8.43.85.186/24
      gateway: 8.43.85.254

- hosts: softserve.rht.gluster.org
  roles:
  - role: swap_file
    size: 1G
    path: /var/swap   

- hosts: haplometrosis.rht.gluster.org
  roles:
  - role: guest_virt_install
    vars:
      name: softserve.int.rht.gluster.org
    system_disk_size: 10
    mem_size: 2048
    distribution: Centos
    version: 7
    bridge: "{{ bridge_common }}"
    network:
      ip: 172.24.1.65/24
      gateway: 172.24.1.181
      nameservers:
      - 172.24.1.60
      - 172.24.1.61
