---
- hosts: formicary.rht.gluster.org
  roles:
  - role: guest_virt_install
    name: backups.rht.gluster.org
    volgroup: centos
    system_disk_size: 10
    # 1G for pgsql
    # 60G for binary
    # 6G for mls
    # 1G for mysql/wordpress
    data_disk_size: 75
    mem_size: 1024
    num_cpus: 1
    distribution: Centos
    version: 7
    bridge: virbr0
    sshkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    network:
      bootproto: dhcp
  - role: guest_add_bridge
    name: backups.rht.gluster.org
    bridge: "{{ internal_bridge }}"

- hosts: backups.rht.gluster.org
  tasks:
  # uncomment once https://github.com/ansible/ansible/pull/21620 is merged
  #- filesystem:
  #  dev: /dev/vdb
  #  fstype: lvm
  - lvg:
      vg: vg_data_backups.rht.gluster.org
      pvs: /dev/vdb
