---
- hosts: myrmicinae.rht.gluster.org
  roles:
  - role: guest_virt_install
    name: analysis.rht.gluster.org
    system_disk_size: 6
    data_disk_size: 20
    mem_size: 1024
    num_cpus: 1
    distribution: Centos
    version: 7
    bridge: virbr1
    network:
      bootproto: static
      ip: 8.43.85.176/24
      gateway: 8.43.85.254

#- hosts: analysis.rht.gluster.org
#  roles:
#  - role: static_analysis
