- hosts: web
  roles:
  # used for wordpress
  - memcached
  - mariadb
  - role: httpd_blog
    website_domain: oldblog.gluster.org
    document_root: /var/www/html
    server_aliases:
    - community.gluster.org
 
