---
- hosts: proxy_ha
  roles:
  - role: keepalived
    master: proxy01.rht.gluster.org
    group: proxy_ha
    vip:
      public:
        interface: eth0
        address: 8.43.85.185
        prefix: 24

  - role: network_conf_ifcfg
    interface: eth1
    ip: "{{ internal_ip }}/24"
    # since firewalld modify the file, we need to not revert the change 
    when: ansible_eth1.ipv4.address != internal_ip

  - role: cert_syncer
    group: proxy_ha
    interface: eth1

  - role: nginx_proxy_vhost
    domain: fstat.proxy.gluster.org
    backends:
    - fstat.rht.gluster.org

  - role: nginx_proxy_vhost
    domain: docs.proxy.gluster.org
    backends:
    - gluster.readthedocs.io

  - role: nginx_proxy_vhost
    domain: docs.gluster.org
    backends:
    - gluster.readthedocs.io

  - role: nginx_proxy_vhost
    domain: bits.gluster.org
    backends:
    - bits.int.rht.gluster.org

  - role: nginx_proxy_vhost
    domain: ci-logs.gluster.org
    backends:
    - http.int.rht.gluster.org

  - role: nginx_proxy_vhost
    domain: fstat.gluster.org
    backends:
    - fstat.rht.gluster.org
    generate_certificates: False

  - role: nginx_proxy_vhost
    domain: softserve.gluster.org
    backends:
    - softserve.rht.gluster.org
    generate_certificates: False
