---
- hosts: haplometrosis.rht.gluster.org
  roles:
  - role: guest_jenkins_builder_int_rht
    number: 0
    version: 6
  - role: guest_jenkins_builder_int_rht
    number: 1
    version: 6

  - role: guest_jenkins_builder_int_rht
    number: 2
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 3
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 4
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 5
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 6
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 7
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 8
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 9
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 10
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 11
    version: 6
  - role: guest_jenkins_builder_int_rht
    number: 12
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 13
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 14
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 15
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 16
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 17
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 18
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 19
    version: 7

- hosts: pleometrosis.rht.gluster.org
  roles:
  - role: guest_jenkins_builder_int_rht
    number: 20
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 21
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 22
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 23
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 24
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 25
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 26
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 27
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 28
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 29
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 30
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 31
    version: 6
  - role: guest_jenkins_builder_int_rht
    number: 32
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 33
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 34
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 35
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 36
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 37
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 38
    version: 7
  - role: guest_jenkins_builder_int_rht
    number: 39
    version: 7



- hosts: jenkins_builders_rht
  tasks:
  - name: Resize the disk of the builders
    lvol:
      vg: "vg_root_{{ ansible_fqdn }}"
      lv: root
      size: 18G
    when: ansible_system == 'Linux'
  - name: Make sure the filesystem is resized
    filesystem:
      fstype: ext4
      dev: "/dev/mapper/vg_root_{{ ansible_fqdn }}-root"
      resizefs: True
    when: ansible_system == 'Linux'

