---
- hosts: myrmicinae.rht.gluster.org
  roles:
  - role: guest_virt_install
    name: bugziller.rht.gluster.org
    volgroup: "{{ vm_storage_vg }}"
    system_disk_size: 10
    mem_size: 1024
    num_cpus: 1
    distribution: Centos
    version: 7
    bridge: "{{ bridge_public }}"
    sshkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    network:
      bootproto: static
      ip: 8.43.85.178/24
      gateway: 8.43.85.254
      nameservers:
      - 8.8.8.8
      - 8.8.4.4
