---
- hosts: formicary.rht.gluster.org
  roles:
  - role: guest_firewall_rht
    name: masa.rht.gluster.org
    network: 
      bootproto: static
      ip: 8.43.85.179/24
      gateway: 8.43.85.254
      nameservers:
      - 8.8.8.8
      - 8.8.4.4

- hosts: myrmicinae.rht.gluster.org
  roles:
  - role: guest_firewall_rht
    name: mune.rht.gluster.org
    network: 
      bootproto: static
      ip: 8.43.85.180/24
      gateway: 8.43.85.254
      nameservers:
      - 8.8.8.8
      - 8.8.4.4
