---
- hosts: myrmicinae.rht.gluster.org
  roles:
  - role: guest_virt_install
    name: http.int.rht.gluster.org
    system_disk_size: 8
    data_disk_size: 30
    mem_size: 1024
    num_cpus: 1
    distribution: Centos
    version: 7
    bridge: "{{ bridge_common }}"
    network:
      bootproto: static
      ip: 172.24.1.55/24
      gateway: 172.24.1.181

#- hosts: analysis.rht.gluster.org
#  roles:
#  - role: static_analysis
