- hosts: squid_unbound
  roles:
  - role: keepalived
    master: squid01.int.rht.gluster.org
    group: squid_unbound
    vip:
      public:
        interface: eth0
        address: 172.24.1.62
        prefix: 24
  - squid
  - unbound
  - unbound_munin
