---
- package:
    name: "{{ item }}"
    state: present
  with_items:
  - mod_security
  notify: verify config and restart httpd
  name: Install mod_security packages

- name: Install the config file for httpd based blacklist 
  template:
    dest: /etc/httpd/conf.d/{{ _website_domain }}.conf.d/blacklist_spam.conf
    src: dnsbl.conf
  notify: verify config and restart httpd

# https://www.debuntu.org/how-to-prevent-spam-with-apaches-mod-security/
