- openssl_privatekey:
    path: "/etc/openvpn/client/{{ vpn_name }}.key"

- openssl_csr:
    path: "/etc/openvpn/client/{{ vpn_name }}.csr"
    privatekey_path: "/etc/openvpn/client/{{ vpn_name }}.key"
    subject:
      commonName: "{{ inventory_hostname }}"

- command: "cat /etc/openvpn/client/{{ vpn_name }}.csr"
  register: csr

- copy:
    dest: "/etc/openvpn/server/{{ vpn_name }}_{{ inventory_hostname }}.csr"
    content: "{{ csr.stdout }}"
  delegate_to: "{{ remote }}"


- openssl_certificate:
    path: "/etc/openvpn/server/{{ vpn_name }}_{{ inventory_hostname }}.crt"
    csr_path: "/etc/openvpn/server/{{ vpn_name }}_{{ inventory_hostname }}.csr"
    ownca_privatekey_path: "/etc/openvpn/server/{{ vpn_name }}.ca.key"
    ownca_path: "/etc/openvpn/server/{{ vpn_name }}.ca.crt"
    provider: ownca
    selfsigned_digest: sha256
# delegate to
  delegate_to: "{{ remote }}"

- command: "cat /etc/openvpn/server/{{ vpn_name }}_{{ inventory_hostname }}.crt"
  register: crt
  delegate_to: "{{ remote }}"

- copy:
    dest: "/etc/openvpn/client/{{ vpn_name }}.crt"
    content: "{{ crt.stdout }}"

- command: "cat /etc/openvpn/server/{{ vpn_name }}.ca.crt"
  register: ca_crt
  delegate_to: "{{ remote }}"

- copy:
    dest: "/etc/openvpn/client/{{ vpn_name }}.ca.crt"
    content: "{{ ca_crt.stdout }}"


