---
# si server
# faire un certif server avec ansible
#  ca ca.crt
#  cert opentodo-vpn.crt
- openssl_dhparam:
    path: "/etc/openvpn/server/{{ vpn_name }}.dhparams.pem"
    size: 2048

# CA stuff
- openssl_privatekey:
    path: "/etc/openvpn/server/{{ vpn_name }}.ca.key"

# need pyopenssl in EL 8
- openssl_csr:
    path: "/etc/openvpn/server/{{ vpn_name }}.ca.csr"
    privatekey_path: "/etc/openvpn/server/{{ vpn_name }}.ca.key"
    subject:
      commonName: "{{ inventory_hostname }}-{{ vpn_name }}-OpenVPN-CA"
    basic_constraints:
    - 'CA:TRUE'
    basic_constraints_critical: yes


- openssl_certificate:
    path: "/etc/openvpn/server/{{ vpn_name }}.ca.crt"
    csr_path: "/etc/openvpn/server/{{ vpn_name }}.ca.csr"
    privatekey_path: "/etc/openvpn/server/{{ vpn_name }}.ca.key"
    provider: selfsigned
    selfsigned_digest: sha256

# non CA
- openssl_privatekey:
    path: "/etc/openvpn/server/{{ vpn_name }}.key"


- openssl_csr:
    path: "/etc/openvpn/server/{{ vpn_name }}.csr"
    privatekey_path: "/etc/openvpn/server/{{ vpn_name }}.key"
    subject:
      commonName: "{{ inventory_hostname }}"

- openssl_certificate:
    path: "/etc/openvpn/server/{{ vpn_name }}.crt"
    csr_path: "/etc/openvpn/server/{{ vpn_name }}.csr"
    ownca_privatekey_path: "/etc/openvpn/server/{{ vpn_name }}.ca.key"
    ownca_path: "/etc/openvpn/server/{{ vpn_name }}.ca.crt"
    provider: ownca
    selfsigned_digest: sha256

- name: Open the firewall using firewalld
  firewalld:
    port: "1194/tcp"
    permanent: true
    state: enabled
    immediate: yes

